Repository mantvydasdeltuva/guidal, pull requests merged in 2024-12, with the labels that each got.

#2 MDE/feature/Menu
  app/src/main/java/com/guidal/app/graphs/MenuNavGraph.kt
  core/ui/src/main/java/com/guidal/core/ui/components/MenuButton.kt
  core/ui/src/main/java/com/guidal/core/ui/components/TopAppBar.kt
  core/ui/src/main/java/com/guidal/core/ui/models/UiModelMenuButtonIcon.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/about_outlined_icon.xml
  core/ui/src/main/res/drawable/privacy_outlined_icon.xml
  core/ui/src/main/res/drawable/profile_outlined_icon.xml
  core/ui/src/main/res/drawable/settings_outlined_icon.xml
  core/ui/src/main/res/drawable/support_outlined_icon.xml
  core/ui/src/main/res/values/dimens.xml
  feature/menu/src/main/java/com/guidal/feature/menu/main/MainScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/main/MainUiState.kt
  feature/menu/src/main/java/com/guidal/feature/menu/main/MainViewModel.kt
  feature/menu/src/main/res/values/strings.xml
Labels: enhancement, feature

#3 MDE/feature/profile
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/guidal/app/graphs/MenuNavGraph.kt
  core/ui/src/main/java/com/guidal/core/ui/components/MenuButton.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/delete_outlined_icon.xml
  core/ui/src/main/res/drawable/edit_outlined_icon.xml
  core/ui/src/main/res/drawable/email_outlined_icon.xml
  core/ui/src/main/res/drawable/gender_man_icon.xml
  core/ui/src/main/res/drawable/gender_other_icon.xml
  core/ui/src/main/res/drawable/gender_woman_icon.xml
  core/ui/src/main/res/drawable/id_outlined_icon.xml
  core/ui/src/main/res/drawable/language_greece_icon.xml
  core/ui/src/main/res/drawable/language_lithuania_icon.xml
  core/ui/src/main/res/drawable/language_other_icon.xml
  core/ui/src/main/res/drawable/password_outlined_icon.xml
  core/ui/src/main/res/drawable/redirect_outlined_icon.xml
  data/src/main/java/com/guidal/data/di/UtilsModule.kt
  data/src/main/java/com/guidal/data/utils/DataStoreUtils.kt
  feature/authentication/src/main/java/com/guidal/authentication/authentication/AuthenticationScreen.kt
  feature/authentication/src/main/java/com/guidal/authentication/authentication/AuthenticationViewModel.kt
  feature/authentication/src/main/java/com/guidal/authentication/login/LoginScreen.kt
  feature/authentication/src/main/java/com/guidal/authentication/login/LoginViewModel.kt
  feature/home/src/main/java/com/guidal/feature/home/main/MainScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/main/MainScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/profile/ProfileScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/profile/ProfileUiState.kt
  feature/menu/src/main/java/com/guidal/feature/menu/profile/ProfileViewModel.kt
Labels: enhancement, feature, refactor

#4 JTE/feature/homescreen_buttons
  core/ui/src/main/java/com/guidal/core/ui/components/HomeNavigationButton.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/beach_icon.xml
  core/ui/src/main/res/drawable/circled_star_icon.xml
  core/ui/src/main/res/drawable/commute_icon.xml
  core/ui/src/main/res/drawable/favorite_outlined_icon.xml
  core/ui/src/main/res/drawable/hiking_icon.xml
  core/ui/src/main/res/drawable/museum_icon.xml
  core/ui/src/main/res/drawable/nightlife_icon.xml
  core/ui/src/main/res/drawable/restaurant_icon.xml
  core/ui/src/main/res/drawable/shop_icon.xml
  core/ui/src/main/res/values/dimens.xml
  feature/authentication/src/main/java/com/guidal/authentication/authentication/AuthenticationScreen.kt
  feature/authentication/src/main/res/values/strings.xml
  feature/home/src/main/java/com/guidal/feature/home/main/HomeNavigationButtonModel.kt
  feature/home/src/main/java/com/guidal/feature/home/main/MainScreen.kt
  feature/home/src/main/res/values/strings.xml
Labels: feature

#5 MDE/feature/about
  app/build.gradle.kts
  app/src/main/java/com/guidal/app/graphs/MenuNavGraph.kt
  app/src/main/java/com/guidal/app/graphs/RootNavGraph.kt
  core/ui/src/main/java/com/guidal/core/ui/components/MenuButton.kt
  core/ui/src/main/java/com/guidal/core/ui/components/TopAppBar.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/guidal_inline_icon.xml
  feature/menu/src/main/java/com/guidal/feature/menu/about/AboutScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/about/AboutUiState.kt
  feature/menu/src/main/java/com/guidal/feature/menu/about/AboutViewModel.kt
  feature/menu/src/main/java/com/guidal/feature/menu/main/MainScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/profile/ProfileScreen.kt
  feature/menu/src/main/res/values/strings.xml
Labels: feature, refactor

#6 MDE/feature/privacy
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/guidal/app/graphs/MenuNavGraph.kt
  app/src/main/java/com/guidal/app/graphs/RootNavGraph.kt
  core/ui/src/main/java/com/guidal/core/ui/components/Switch.kt
  feature/home/src/main/java/com/guidal/feature/home/main/MainScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/privacy/PrivacyScreen.kt
  feature/menu/src/main/java/com/guidal/feature/menu/privacy/PrivacyUiState.kt
  feature/menu/src/main/java/com/guidal/feature/menu/privacy/PrivacyViewModel.kt
  feature/menu/src/main/res/values/strings.xml
Labels: feature, refactor
