Repository mantvydasdeltuva/guidal, pull requests merged in 2025-02, with the labels that each got.

#19 feature/location-sensor
  feature/discover/src/main/AndroidManifest.xml
  feature/discover/src/main/java/com/guidal/feature/discover/main/MainScreen.kt
Labels: enhancement

#20 feature/notifications
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/guidal/app/GuidalApplication.kt
  data/src/main/java/com/guidal/data/api/services/NotificationService.kt
  data/src/main/java/com/guidal/data/db/repositories/ForecastRepository.kt
  data/src/main/java/com/guidal/data/di/DatabaseModule.kt
  data/src/main/res/drawable/guidal_icon.xml
  feature/menu/src/main/java/com/guidal/feature/menu/about/AboutScreen.kt
  gradle/libs.versions.toml
  secrets.properties
Labels: enhancement

#22 JTE/feature/locationView
  .gitignore
  app/src/main/java/com/guidal/app/graphs/DiscNavGraph.kt
  app/src/main/java/com/guidal/app/graphs/HomeNavGraph.kt
  app/src/main/java/com/guidal/app/graphs/RootNavGraph.kt
  core/ui/src/main/java/com/guidal/core/ui/components/InTextButton.kt
  core/ui/src/main/java/com/guidal/core/ui/components/LocationPreviewCard.kt
  core/ui/src/main/java/com/guidal/core/ui/components/RatingBar.kt
  core/ui/src/main/java/com/guidal/core/ui/models/UiModelInTextButtonIcon.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/price_tag_outlined_icon.xml
  core/ui/src/main/res/drawable/sample_image.jpg
  feature/discover/src/main/java/com/guidal/feature/discover/main/MainScreen.kt
  feature/discover/src/main/res/values-lt/strings.xml
  feature/discover/src/main/res/values/strings.xml
  feature/home/src/main/java/com/guidal/feature/home/location/list/LocationListScreen.kt
  feature/home/src/main/java/com/guidal/feature/home/location/list/LocationListUiState.kt
  feature/home/src/main/java/com/guidal/feature/home/location/list/LocationListViewModel.kt
  feature/home/src/main/java/com/guidal/feature/home/location/view/LocationViewScreen.kt
  feature/home/src/main/java/com/guidal/feature/home/location/view/LocationViewUiState.kt
  feature/home/src/main/java/com/guidal/feature/home/location/view/LocationViewViewModel.kt
  feature/home/src/main/java/com/guidal/feature/home/main/MainScreen.kt
Labels: feature

#24 JTE/feature/dynamicLocationImages
  core/ui/src/main/java/com/guidal/core/ui/components/LocationPreviewCard.kt
  feature/discover/src/main/java/com/guidal/feature/discover/main/MainScreen.kt
  feature/discover/src/main/res/values-lt/strings.xml
  feature/discover/src/main/res/values/strings.xml
  feature/home/src/main/java/com/guidal/feature/home/location/list/LocationListScreen.kt
  feature/home/src/main/java/com/guidal/feature/home/location/view/LocationViewScreen.kt
  feature/home/src/main/res/drawable/image_location_3.jpg
  feature/home/src/main/res/drawable/sample_image.jpg
  feature/home/src/main/res/values-lt/strings.xml
Labels: enhancement

#25 JTE/feature/detailedLocations
  core/ui/src/main/java/com/guidal/core/ui/components/LocationPreviewCard.kt
  core/ui/src/main/java/com/guidal/core/ui/theme/Icon.kt
  core/ui/src/main/res/drawable/schedule_icon.xml
  data/src/main/java/com/guidal/data/db/Callback.kt
  data/src/main/java/com/guidal/data/db/migrations/Migration4To5.kt
  feature/home/src/main/java/com/guidal/feature/home/location/view/LocationViewScreen.kt
  feature/home/src/main/res/drawable/image_location_1.png
  feature/home/src/main/res/drawable/image_location_10.jpg
  feature/home/src/main/res/drawable/image_location_11.jpg
  feature/home/src/main/res/drawable/image_location_12.jpg
  feature/home/src/main/res/drawable/image_location_13.jpg
  feature/home/src/main/res/drawable/image_location_14.jpg
  feature/home/src/main/res/drawable/image_location_15.jpg
  feature/home/src/main/res/drawable/image_location_16.jpg
  feature/home/src/main/res/drawable/image_location_17.jpg
  feature/home/src/main/res/drawable/image_location_18.jpg
  feature/home/src/main/res/drawable/image_location_19.jpg
  feature/home/src/main/res/drawable/image_location_2.jpg
  feature/home/src/main/res/drawable/image_location_20.jpg
  feature/home/src/main/res/drawable/image_location_21.jpg
  feature/home/src/main/res/drawable/image_location_22.jpg
  feature/home/src/main/res/drawable/image_location_23.jpg
  feature/home/src/main/res/drawable/image_location_24.jpg
  feature/home/src/main/res/drawable/image_location_25.jpg
  feature/home/src/main/res/drawable/image_location_26.jpg
  feature/home/src/main/res/drawable/image_location_27.jpg
  feature/home/src/main/res/drawable/image_location_28.jpg
  feature/home/src/main/res/drawable/image_location_29.jpg
  feature/home/src/main/res/drawable/image_location_30.jpg
  feature/home/src/main/res/drawable/image_location_31.jpg
  feature/home/src/main/res/drawable/image_location_32.jpg
  feature/home/src/main/res/drawable/image_location_33.jpg
  feature/home/src/main/res/drawable/image_location_34.jpg
  feature/home/src/main/res/drawable/image_location_4.jpg
  feature/home/src/main/res/drawable/image_location_5.jpg
  feature/home/src/main/res/drawable/image_location_6.jpg
  feature/home/src/main/res/drawable/image_location_7.jpg
  feature/home/src/main/res/drawable/image_location_8.jpg
  feature/home/src/main/res/drawable/image_location_9.jpg
Labels: enhancement

#26 Create LICENSE
  LICENSE
Labels: docs
